### ISSUE TITLE
Stream51 instance incremental

### ISSUE THREAD

**Issue by arthurdouillard** [Continvvm/continuum#106]
Right now we can do instance incr with stream51 by clip or video id. Not sure if that's the right way to do according to Hayes? We should ask her

**Comment by TLESORT** [comment]
OK there are problems right now with the scenarios created because clip_id , frame_num or video_num are relative numbers in the json file and they are used as absolute number

**Comment by TLESORT** [comment]
- [ ] convert relatives id to absolut ids
- [ ] check if images are correctly ordered while sampled in tasksets
- [ ] double check cropping (some are really not good and some images are completely black (baleines))
- [ ] il faut recreer les scenarios instance et instances class de stream 51

**Comment by TLESORT** [comment]
I reused the stream51 branch for dev
