### ISSUE TITLE
Test on class incremental learning

### ISSUE THREAD

**Issue by mugnaidaniele** [Continvvm/continuum#118]
Hi, 
congratulations for this project, it's really well done. 
I'm working on class incremental learning problem. I have a question: how can i test my model on all the classes until the current task?

**Comment by TLESORT** [comment]
Hi @mugnaidaniele,
thanks for the positive feedback! It is appreciated :D
You can create a task set `task_set=cl_scenario_test[:ind_task]`, it will contains the data from all tasks from 0 to ind_task.
Then, you can iterate the task set to test your model.

Does it answer you question?

**Comment by arthurdouillard** [comment]
Please note that `task_set = cl_scenario_test[:ind_task]` contains tasks [0, ind_task[, the latter is excluded as it would have with most python slicing. To include ind_task also, do `task_set = cl_scenario_test[:ind_task + 1]`
