### ISSUE TITLE
Core50 missing one task

### ISSUE THREAD

**Issue by psychicmario** [Continvvm/continuum#123]
Hey, this is such a minor fix but Core50 actually has 8 training tasks. Your current code for the Core50 class only has the domain id go up to 10, but there is actually domain id 11. You just need to change the domain id in range(10) to range(11)

**Comment by arthurdouillard** [comment]
Hey!

Thank you for your report, you're right.
I've fixed it in PR #124 which will be merged as soon as @TLESORT accept it.

**Comment by arthurdouillard** [comment]
(you can update continuum to 1.0.14)

**Comment by psychicmario** [comment]
Thanks for the prompt fix Arthur :)
