### ISSUE TITLE
Adding CUB200 dataset

### ISSUE THREAD

**Issue by TLESORT** [Continvvm/continuum#146]

**Comment by arthurdouillard** [comment]
This kind of dataset is interesting because of the attributes it has in addition of the labels. We may want to think how to integrate that. In the dataset, or in the scenario?

**Comment by TLESORT** [comment]
First in dataset and after maybe we can use attributs to create specific scenarios

**Comment by TLESORT** [comment]
Attributes on CUB200 are not so simple to use, we can create specific scenario with attributes on another dataset.
