### ISSUE TITLE
rehearsal based methods support

### ISSUE THREAD

**Issue by zhaoedf** [Continvvm/continuum#155]
Hi, after reading your code, i find it convenient and elegant. 

Due to the need of training some rehearsal based methods, i need to add the exemplar sets into the new training set each increment. i was wondering if the continuum supports such behavior?(As far as i read the code, i found nothing related to this need.)

**Comment by arthurdouillard** [comment]
Hey, thanks for the kind words.

We don't have yet this features, but I think I could quickly integrate my code doing that in Continuum. If I can find time, this could be done this week.

**Comment by TLESORT** [comment]
Hi @zhaoedf ,

The way I do it with the current version of the library is to create a separate memory with the `TaskSet` class and add data incrementally and merge it with the current taskset at the beginning of a new task.

The code is somehow similar to:
```
from continuum import TaskSet

for task_id, taskset in enumerate(scenario):
     # samples2memorize 
     x, y, t = some_function(taskset)
     if task_id == 0:
        memory_set = TaskSet(x, y, t, taskset.trsf, data_type=taskset.data_type)
     else:
        # add memory into taskset
        taskset.concat(memory_set )
        
        # add samples into memory 
        memory_set.add_samples(x, y, t)
        
     loader = DataLoader(taskset)
     [...]
```
The doc about taskset it here : https://continuum.readthedocs.io/en/latest/_tutorials/tasks/tasks.html

We can add some supplementary features for rehearsal with PR https://github.com/Continvvm/continuum/pull/156 by @arthurdouillard, but I think that the basic stuff is already doable with the current version of the code.
Or did I miss something?

**Comment by zhaoedf** [comment]
> Hi @zhaoedf ,
> 
> The way I do it with the current version of the library is to create a separate memory with the `TaskSet` class and add data incrementally and merge it with the current taskset at the beginning of a new task.
> 
> The code is somehow similar to:
> 
> ```
> from continuum import TaskSet
> 
> for task_id, taskset in enumerate(scenario):
>      # samples2memorize 
>      x, y, t = some_function(taskset)
>      if task_id == 0:
>         memory_set = TaskSet(x, y, t, taskset.trsf, data_type=taskset.data_type)
>      else:
>         # add memory into taskset
>         taskset.concat(memory_set )
>         
>         # add samples into memory 
>         memory_set.add_samples(x, y, t)
>         
>      loader = DataLoader(taskset)
>      [...]
> ```
> 
> The doc about taskset it here : https://continuum.readthedocs.io/en/latest/_tutorials/tasks/tasks.html
> 
> We can add some supplementary features for rehearsal with PR #156 by @arthurdouillard, but I think that the basic stuff is already doable with the current version of the code.
> Or did I miss something?



> Hi @zhaoedf ,
> 
> The way I do it with the current version of the library is to create a separate memory with the `TaskSet` class and add data incrementally and merge it with the current taskset at the beginning of a new task.
> 
> The code is somehow similar to:
> 
> ```
> from continuum import TaskSet
> 
> for task_id, taskset in enumerate(scenario):
>      # samples2memorize 
>      x, y, t = some_function(taskset)
>      if task_id == 0:
>         memory_set = TaskSet(x, y, t, taskset.trsf, data_type=taskset.data_type)
>      else:
>         # add memory into taskset
>         taskset.concat(memory_set )
>         
>         # add samples into memory 
>         memory_set.add_samples(x, y, t)
>         
>      loader = DataLoader(taskset)
>      [...]
> ```
> 
> The doc about taskset it here : https://continuum.readthedocs.io/en/latest/_tutorials/tasks/tasks.html
> 
> We can add some supplementary features for rehearsal with PR #156 by @arthurdouillard, but I think that the basic stuff is already doable with the current version of the code.
> Or did I miss something?

sorry for the late reply(compared with your fast reponse) :) 
From your new code and TLESORT's code, i think it is enough for my need.

Besides, i read TLESORT's comments about the code changes and i assume that the code about rehearsal and herding is not the final version? Thus, it is still not available on pip? right?

**Comment by arthurdouillard** [comment]
Not yet available, we are still discussing the right way to do it. But it will probably be finished soon.

If you're really in a hurry you can copy-paste the code from this PR into your codebase.

**Comment by zhaoedf** [comment]
> Not yet available, we are still discussing the right way to do it. But it will probably be finished soon.
> 
> 
> 
> If you're really in a hurry you can copy-paste the code from this PR into your codebase.

oh you simple code above is enough for me. by the way, it would be better if you add the concat api of class taskset in the doc
