### ISSUE TITLE
CTrL Out is not correct

### ISSUE THREAD

**Issue by ashok-arjun** [Continvvm/continuum#163]
In the CTrL_out split in the CTrL dataset, the last task must have its labels different from the original task.

The [implementation](https://github.com/Continvvm/continuum/blob/master/continuum/datasets/ctrl.py#L230) of `CTRLout` does not do that.

**Comment by arthurdouillard** [comment]
Hey, thanks for the issue and your interest in Continuum.

It is already the case. Look at the class counters: https://github.com/Continvvm/continuum/blob/master/continuum/datasets/ctrl.py#L255 .

You can quickly see with the following code snippet that the first and last task have different labels:

```python
from continuum.datasets import CTRLminus, CTRLplus, CTRLplastic, CTRLin, CTRLout
from continuum import ContinualScenario
import numpy as np

scenario_train = ContinualScenario(CTRLout("/local/douillard/", split="train", download=True))

for taskset in scenario_train:
    print(np.unique(taskset._y))
```

Best,
