### ISSUE TITLE
about using scenario in distributed training settings.

### ISSUE THREAD

**Issue by zhaoedf** [Continvvm/continuum#181]
hi, i recently using continuum for distributing training(i.e. ddp with pytorchlightning), and i found that it seems every process of ddp will all create a scenario, which will cause not only a resource shortage problem, but also a intterupt in dataloader.
So i was wondering if the continuum is tested in distributed environment?

**Comment by arthurdouillard** [comment]
Hey,

That's weird because I also DistributedDataParallel and Continuum and I haven't seen any interrupt in the data loader.

Although I've never used PytorchLightning. Could you provide a minimal example with that library that uses DDP and continuum?

**Comment by zhaoedf** [comment]
> Hey,
> 
> That's weird because I also DistributedDataParallel and Continuum and I haven't seen any interrupt in the data loader.
> 
> Although I've never used PytorchLightning. Could you provide a minimal example with that library that uses DDP and continuum?


well, after i posted this problem, i began to realize that i might not be particularly clear about how ddp works. 
i mean i know that ddp will create a process in each gpu, where there will be a same code and a same model parameters. for me, i think that every part of the code, unless you specify that certain code only runs on rank_zero, will all run on each gpu.
since we know that using continuum, one needs to create a "scenario" first. thus, this action will run on each gpu and get multiple copies of scenarios(not sure if i am correct, correct me if i am wrong.). is it possible that something went wrong here?

**by the way, could you give me a glance(certain part is ok for me) about the code you used in ddp with continuum?** i am afraid i can't find a minimal example due to the environment issue and code implementation problem.

**Comment by arthurdouillard** [comment]
The code is super big and messy so hard to share. But I've really didn't not make any changes to how continuum is used for ddp.

Although, I'm currently working only on CIFAR100 and not a large dataset. But It shouldn't be a problem because usually for large datasets like ImageNet only metadata are loaded (and thus would be duplicated) in RAM. What dataset do you use?

Could you try maybe to create the dataset on only one gpu? Likewise:

```
import torch.distributed as dist

if dist.get_rank() == 0:
  ... create dataset & scenario

```

**Comment by zhaoedf** [comment]
> The code is super big and messy so hard to share. But I've really didn't not make any changes to how continuum is used for ddp.
> 
> 
> 
> Although, I'm currently working only on CIFAR100 and not a large dataset. But It shouldn't be a problem because usually for large datasets like ImageNet only metadata are loaded (and thus would be duplicated) in RAM. What dataset do you use?
> 
> 
> 
> Could you try maybe to create the dataset on only one gpu? Likewise:
> 
> 
> 
> ```
> 
> import torch.distributed as dist
> 
> 
> 
> if dist.get_rank() == 0:
> 
>   ... create dataset & scenario
> 
> 
> 
> ```

i use cifar100 as well. i will try your code, but i wonder, will there be any sync issue, since the process of creating dataset and scenario only exists on rank 0 device?

**Comment by arthurdouillard** [comment]
How much RAM do you have?
Anyway for class incremental + cifar, continuum computes really nothing and is just a wrapper over torchvision's CIFAR100. 

Have you tried to use the torchvision's cifar100 with your ddp system? I think you'll sill have your problem.

> i use cifar100 as well. i will try your code, but i wonder, will there be any sync issue, since the process of creating dataset and scenario only exists on rank 0 device?

Yeah you're probably right.

**Comment by zhaoedf** [comment]
> How much RAM do you have?
> Anyway for class incremental + cifar, continuum computes really nothing and is just a wrapper over torchvision's CIFAR100.
> 
> Have you tried to use the torchvision's cifar100 with your ddp system? I think you'll sill have your problem.
> 
> > i use cifar100 as well. i will try your code, but i wonder, will there be any sync issue, since the process of creating dataset and scenario only exists on rank 0 device?
> 
> Yeah you're probably right.

torchvision cifar100 works well for me. well, i think maybe i will just not use pytorch-lightning instead.

**Comment by arthurdouillard** [comment]
Can you give me access to your code? Or a minimal example so I can reproduce the error?

**Comment by zhaoedf** [comment]
> Can you give me access to your code? Or a minimal example so I can reproduce the error?

it might need some time, i will post the code ASAP.

**Comment by arthurdouillard** [comment]
no worry

**Comment by TLESORT** [comment]
I close this issue because of inactivity feel free to reopen it if needed.
