### ISSUE TITLE
bug in _reduce method memory.py. Unwanted removal of exemplars in some cases. 

### ISSUE THREAD

**Issue by sameerkhnl** [Continvvm/continuum#243]
In memory.py, _reduce method (when fixed_memory = False),  if len(indexes) <= self.memory_per_class then you lose all the stored exemplars for that class since no value is appended. As a quickfix for my project, I have added an else condition. else: x.append(self._x[indexes]), similarly for y and t.

**Comment by arthurdouillard** [comment]
Hello, this was indeed a bug, but we fixed it 15 days ago.

See this commit: https://github.com/Continvvm/continuum/commit/c63098d91148148566221f2889d81d6992526091

**Comment by arthurdouillard** [comment]
I guess that the fix wasn't uploaded on pypi, our bad. I've released the 1.1.7 that fix this bug.
