### ISSUE TITLE
possible bugs in herding.py

### ISSUE THREAD

**Issue by zhaoedf** [Continvvm/continuum#251]
https://github.com/Continvvm/continuum/blob/master/continuum/rehearsal/herding.py

inside the function of **herd_random and herd_closest_to_cluster**, the mean is computed as the following pic, which i think is probably wrong. 

**The correct axis should 0 instead of 1.**

The red box in the pic below indicates that the features is a matrix like (bs, feature_dim), so the mean should be computer "along" the axis of 0 instead of1.

![image](https://user-images.githubusercontent.com/48846150/142717174-90ef38ec-8949-4f95-a96c-49dcbb799a9a.png)

another proof is that when you look into the function **herd_closest_to_barycenter**, you can see the mean is computed stiil along axis 1, but the input array is transposed before beforehand.
![image](https://user-images.githubusercontent.com/48846150/142717360-187072e0-8531-4c0c-9556-8e7e7e8b566e.png)

**Comment by arthurdouillard** [comment]
Hello,

You're right!

However, it only affects herd_closest_to_cluster, not herd_random.

**Comment by zhaoedf** [comment]
> Hello,
> 
> You're right!
> 
> However, it only affects herd_closest_to_cluster, not herd_random.

my bad 😂

**Comment by arthurdouillard** [comment]
No worries, thank you for finding this bug :)
