### ISSUE TITLE
Error on quick example

### ISSUE THREAD

**Issue by ibnudaqiqil** [Continvvm/continuum#257]
I just install and run quick example form documentation and get this error 

```bash
#python replay_vae_mnist.py 
Traceback (most recent call last):
  File "D:\xxxxxy\replay_vae_mnist.py", line 8, in <module>
    from continuum.datasets import MNIST, CIFAR10, CIFAR100, KMNIST, FashionMNIST, InMemoryDataset
  File "C:\Anaconda3\envs\pytorch\lib\site-packages\continuum\__init__.py", line 11, in <module>
    from continuum.scenarios import *
  File "C:\Anaconda3\envs\pytorch\lib\site-packages\continuum\scenarios\__init__.py", line 13, in <module>
    from continuum.scenarios import hf
  File "C:\Anaconda3\envs\pytorch\lib\site-packages\continuum\scenarios\hf\__init__.py", line 3, in <module>
    from continuum.scenarios.hf.huggingface_fellowship import HuggingFaceFellowship
  File "C:\Anaconda3\envs\pytorch\lib\site-packages\continuum\scenarios\hf\huggingface_fellowship.py", line 4, in <module>
    from datasets.arrow_dataset import Dataset as HFDataset
ModuleNotFoundError: No module named 'datasets.arrow_dataset'
```

**Comment by TLESORT** [comment]
Hi @ibnudaqiqil , thanks for reporting this issue :)

I am not able to reproduce your import error with:
```
from continuum.datasets import MNIST, CIFAR10, CIFAR100, KMNIST, FashionMNIST, InMemoryDataset
```
Did you install all the requirements?
I looks like it comes from the `datasets` library from huggingface, Maybe you can try to run a :
```
pip install datasets
```
to see if it fix your issue.

**Comment by ibnudaqiqil** [comment]
I have installed the package

(pytorch) λ pip install datasets
Requirement already satisfied: datasets in c:\anaconda3\envs\pytorch\lib\site-packages (1.17.0)
Requirement already satisfied: pyarrow!=4.0.0,>=3.0.0 in c:\anaconda3\envs\pytorch\lib\site-packages (from datasets) (6.0.1)
Requirement already satisfied: xxhash in c:\anaconda3\envs\pytorch\lib\site-packages (from datasets) (2.0.2)
Requirement already satisfied: dill in c:\anaconda3\envs\pytorch\lib\site-packages (from datasets) (0.3.4)
Requirement already satisfied: fsspec[http]>=2021.05.0 in c:\anaconda3\envs\pytorch\lib\site-packages (from datasets) (2021.11.1)
Requirement already satisfied: multiprocess in c:\anaconda3\envs\pytorch\lib\site-packages (from datasets) (0.70.12.2)
Requirement already satisfied: huggingface-hub<1.0.0,>=0.1.0 in c:\anaconda3\envs\pytorch\lib\site-packages (from datasets) (0.2.1)
Requirement already satisfied: pandas in c:\anaconda3\envs\pytorch\lib\site-packages (from datasets) (1.2.4)
Requirement already satisfied: requests>=2.19.0 in c:\anaconda3\envs\pytorch\lib\site-packages (from datasets) (2.25.1)
Requirement already satisfied: tqdm>=4.62.1 in c:\anaconda3\envs\pytorch\lib\site-packages (from datasets) (4.62.3)
Requirement already satisfied: aiohttp in c:\anaconda3\envs\pytorch\lib\site-packages (from datasets) (3.8.1)
Requirement already satisfied: packaging in c:\anaconda3\envs\pytorch\lib\site-packages (from datasets) (20.9)
Requirement already satisfied: numpy>=1.17 in c:\anaconda3\envs\pytorch\lib\site-packages (from datasets) (1.20.1)
Requirement already satisfied: pyyaml in c:\anaconda3\envs\pytorch\lib\site-packages (from huggingface-hub<1.0.0,>=0.1.0->datasets) (5.4.1)
Requirement already satisfied: typing-extensions>=3.7.4.3 in c:\anaconda3\envs\pytorch\lib\site-packages (from huggingface-hub<1.0.0,>=0.1.0->datasets) (4.0.1)
Requirement already satisfied: filelock in c:\anaconda3\envs\pytorch\lib\site-packages (from huggingface-hub<1.0.0,>=0.1.0->datasets) (3.0.12)
Requirement already satisfied: pyparsing>=2.0.2 in c:\anaconda3\envs\pytorch\lib\site-packages (from packaging->datasets) (2.4.7)
Requirement already satisfied: chardet<5,>=3.0.2 in c:\anaconda3\envs\pytorch\lib\site-packages (from requests>=2.19.0->datasets) (4.0.0)
Requirement already satisfied: idna<3,>=2.5 in c:\anaconda3\envs\pytorch\lib\site-packages (from requests>=2.19.0->datasets) (2.10)
Requirement already satisfied: certifi>=2017.4.17 in c:\anaconda3\envs\pytorch\lib\site-packages (from requests>=2.19.0->datasets) (2020.12.5)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\anaconda3\envs\pytorch\lib\site-packages (from requests>=2.19.0->datasets) (1.26.4)
Requirement already satisfied: colorama in c:\anaconda3\envs\pytorch\lib\site-packages (from tqdm>=4.62.1->datasets) (0.4.4)
Requirement already satisfied: charset-normalizer<3.0,>=2.0 in c:\anaconda3\envs\pytorch\lib\site-packages (from aiohttp->datasets) (2.0.9)
Requirement already satisfied: yarl<2.0,>=1.0 in c:\anaconda3\envs\pytorch\lib\site-packages (from aiohttp->datasets) (1.7.2)
Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in c:\anaconda3\envs\pytorch\lib\site-packages (from aiohttp->datasets) (4.0.2)
Requirement already satisfied: aiosignal>=1.1.2 in c:\anaconda3\envs\pytorch\lib\site-packages (from aiohttp->datasets) (1.2.0)
Requirement already satisfied: multidict<7.0,>=4.5 in c:\anaconda3\envs\pytorch\lib\site-packages (from aiohttp->datasets) (5.2.0)
Requirement already satisfied: frozenlist>=1.1.1 in c:\anaconda3\envs\pytorch\lib\site-packages (from aiohttp->datasets) (1.2.0)
Requirement already satisfied: attrs>=17.3.0 in c:\anaconda3\envs\pytorch\lib\site-packages (from aiohttp->datasets) (20.3.0)
Requirement already satisfied: python-dateutil>=2.7.3 in c:\anaconda3\envs\pytorch\lib\site-packages (from pandas->datasets) (2.8.1)
Requirement already satisfied: pytz>=2017.3 in c:\anaconda3\envs\pytorch\lib\site-packages (from pandas->datasets) (2021.1)
Requirement already satisfied: six>=1.5 in c:\anaconda3\envs\pytorch\lib\site-packages (from python-dateutil>=2.7.3->pandas->datasets) (1.15.0)

**Comment by arthurdouillard** [comment]
I've tried with `datasets` both in 1.6.0 (the min version required by Continuum) and 1.17.0 (yours) and it works on my side.

I'm not really sure why it won't work on your side. I'll look into it, but if you have any more info to share, don't hesitate.

**Comment by ibnudaqiqil** [comment]
yeah, this is strange..  i checked in c:\anaconda3\envs\pytorch\lib\site-packages, I can found the missing package

**Comment by ibnudaqiqil** [comment]
this is my path
```
(pytorch) λ python
Python 3.9.4 (default, Apr  9 2021, 11:43:21) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.path
['', 'C:\\Anaconda3\\envs\\pytorch\\python39.zip', 'C:\\Anaconda3\\envs\\pytorch\\DLLs', 'C:\\Anaconda3\\envs\\pytorch\\lib', 'C:\\Anaconda3\\envs\\pytorch', 'C:\\Anaconda3\\envs\\pytorch\\lib\\site-packages', 'C:\\Anaconda3\\envs\\pytorch\\lib\\site-packages\\locket-0.2.1-py3.9.egg', 'C:\\Anaconda3\\envs\\pytorch\\lib\\site-packages\\win32', 'C:\\Anaconda3\\envs\\pytorch\\lib\\site-packages\\win32\\lib', 'C:\\Anaconda3\\envs\\pytorch\\lib\\site-packages\\Pythonwin']
>>>
```

**Comment by ibnudaqiqil** [comment]
i try on our ubuntu server. similar result.
`(base) ibunu_i@dudley1:~/2022/CMGMM_REPLAY$  python replay_vae_mnist.py
Traceback (most recent call last):
  File "replay_vae_mnist.py", line 4, in <module>
    from continuum import ClassIncremental
  File "/home/abelab/ibunu_i/anaconda3/lib/python3.8/site-packages/continuum/__init__.py", line 11, in <module>
    from continuum.scenarios import *
  File "/home/abelab/ibunu_i/anaconda3/lib/python3.8/site-packages/continuum/scenarios/__init__.py", line 13, in <module>
    from continuum.scenarios import hf
  File "/home/abelab/ibunu_i/anaconda3/lib/python3.8/site-packages/continuum/scenarios/hf/__init__.py", line 3, in <module>
    from continuum.scenarios.hf.huggingface_fellowship import HuggingFaceFellowship
  File "/home/abelab/ibunu_i/anaconda3/lib/python3.8/site-packages/continuum/scenarios/hf/huggingface_fellowship.py", line 4, in <module>
    from datasets.arrow_dataset import Dataset as HFDataset
ModuleNotFoundError: No module named 'datasets.arrow_dataset'
`

**Comment by arthurdouillard** [comment]
Can you just import datasets?

Like in a python REPL, type `import datasets`.

What is your `continuum` version?

**Comment by ibnudaqiqil** [comment]
Its ok. No problem

```
D:\CMGMM_Replay (master -> master) 
λ conda activate pytorch

D:\CMGMM_Replay (master -> master) 
(pytorch) λ python
Python 3.9.4 (default, Apr  9 2021, 11:43:21) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import datasets
>>>
```

**Comment by anth2o** [comment]
Hi @ibnudaqiqil , could you please do:
```python
import datasets
print(datasets.__file__)
```
I imagine that you have a a folder `datasets` that is being imported instead of the library

**Comment by arthurdouillard** [comment]
I've done that:

```bash
conda create -y --prefix path_to_env python=3.7 anaconda
conda activate path_to_env
pip install continuum
python -c "from continuum.datasets import MNIST"
```

And it works.

Have you considered what @anth2o suggested? I think it could be the source of your error.

**Comment by ibnudaqiqil** [comment]
yes its work..

**Comment by ibnudaqiqil** [comment]
> Hi @ibnudaqiqil , could you please do:
> 
> ```python
> import datasets
> print(datasets.__path__)
> ```
> 
> I suppose that you have a folder `datasets` that is being imported instead of the library

Ah I see, thank you
