### ISSUE TITLE
Transform MNIST dataset

### ISSUE THREAD

**Issue by ibnudaqiqil** [Continvvm/continuum#259]
i try to transform MNIST, for example 
`dataset = MNIST("./store/dataset", download=True, train=True, transform=transforms.ToTensor())`

but i get error
```
  File "C:\Anaconda3\envs\pytorch\lib\site-packages\continuum\datasets\base.py", line 199, in __init__
    raise ValueError(
ValueError: Don't provide `transform` to the dataset. You should give those to the scenario.
```

Then I add transform in scenario and got
```
    scenario = ClassIncremental(
TypeError: __init__() got an unexpected keyword argument 'transform'
```

**Comment by ibnudaqiqil** [comment]
I found it, its use "transformations",

**Comment by TLESORT** [comment]
Yes, the correct way to do it is:
```
scenario = ClassIncremental(dataset,increment=2,transformations=[transforms.ToTensor()])
```
https://continuum.readthedocs.io/en/latest/_tutorials/scenarios/scenarios.html#classes-incremental

Have a nice day :)
