### ISSUE TITLE
Issues with some logger metrics 

### ISSUE THREAD

**Issue by umbertocappellazzo** [Continvvm/continuum#266]
Hi,
I defined the logger object as shown in the Continuum tutorials for computing the CL metrics. While some metrics work (accuracy and bwt for instance), others don't, in particular average_incremental_accuracy and online_cumulative_performance. I'm going to paste a part of my code where I iterate through some epochs of a specific task/experience. Probably I'm doing some mistakes somewhere. 

```
print(f"Start training for {epochs} epochs")
    for epoch in range(epochs):
            model.train()
            for x,y,t in train_loader:
                x = x.to(device)
                y = y.to(device)
                
                optimizer.zero_grad()
                predictions = model(x)['logits']
                loss = criterion(predictions,y[:,0])
                loss.backward()
                optimizer.step()
                
                
                logger.add([predictions.cpu().argmax(dim=1),y[:,0].cpu(),t], subset= 'train')
                
                # Test phase
            if args.eval_every and epoch % args.eval_every == 0:
                model.eval()
                test_loss = 0.
                with torch.inference_mode(): 
                    for x_test, y_test, t_test in test_loader:
                        predic_test = model(x_test)['logits']
                        test_loss += criterion(predic_test,y_test[:,0].cuda())
                       
                        
                        logger.add([predic_test.cpu().argmax(dim=1),y_test[:,0].cpu(),t], subset = 'test')
                     test_loss /= len(test_loader)
                    print(f"Train accuracy: {logger.online_accuracy}")
                    print(f"Test accuracy: {logger.accuracy}")
            
            print(logger.average_incremental_accuracy)
            print([round(100 * acc_t, 2) for acc_t in logger.accuracy_per_task])
            
            logger.end_epoch()
```

During the second task, I got this error for the average_incremental_accuracy:

```
Traceback (most recent call last):
  File "main.py", line 263, in <module>
    main(args)
  File "main.py", line 222, in main
    print(logger.average_incremental_accuracy)
  File "/home/stek/.local/lib/python3.8/site-packages/continuum/metrics/utils.py", line 11, in wrapper2
    return func(self)
  File "/home/stek/.local/lib/python3.8/site-packages/continuum/metrics/logger.py", line 134, in average_incremental_accuracy
    return statistics.mean([
  File "/home/stek/.local/lib/python3.8/site-packages/continuum/metrics/logger.py", line 135, in <listcomp>
    accuracy(all_preds[t], all_targets[t])
  File "/home/stek/.local/lib/python3.8/site-packages/continuum/metrics/metrics.py", line 14, in accuracy
    assert task_preds.size > 0
AssertionError
```
It seems like the task_preds are not present in the logger.

I'm waiting for your suggestions about the issue. If the code is not sufficient, I can include the entire scripts, but since the logger relies on the predicted and true labels, I don't think the rest of the code is relevant.
Thanks in advance.

**Comment by umbertocappellazzo** [comment]
UPDATE: also forgetting doesn't work. This is the error:

`File "main.py", line 263, in <module>
    main(args)
  File "main.py", line 225, in main
    "forgetting": round(100 * logger.forgetting, 6), 'acc_per_task': [round(100 * acc_t, 2) for acc_t in logger.accuracy_per_task], 
  File "/home/stek/.local/lib/python3.8/site-packages/continuum/metrics/utils.py", line 11, in wrapper2
    return func(self)
  File "/home/stek/.local/lib/python3.8/site-packages/continuum/metrics/logger.py", line 173, in forgetting
    return forgetting(all_preds, all_targets, task_ids)
  File "/home/stek/.local/lib/python3.8/site-packages/continuum/metrics/metrics.py", line 167, in forgetting
    a_kj = _get_R_ij(k - 1, j, all_preds, all_targets, all_tasks)
  File "/home/stek/.local/lib/python3.8/site-packages/continuum/metrics/metrics.py", line 214, in _get_R_ij
    raise ValueError(
ValueError: You haven't evaluated on any samples of task 0 after training on task 2, therefore it is impossible to compute some metrics (e.g. FwT, BwT).
Either don't use those metrics or evaluate on all seen tasks. You can do it one by one (`test_scenario[0], test_scenario[1]`) or all together (`test_scenario[:task_id + 1]`).`

At this point, I think it's incorrect how I use the logger.

**Comment by TLESORT** [comment]
Hi @umbertocappellazzo ,
Sorry for the delay to answer.
I will investigate this later today.
One quick idea, would it work if you do "predictions.cpu()" instead of "predictions.cpu().argmax(dim=1)"?

**Comment by umbertocappellazzo** [comment]
Hi @TLESORT! If I remove .argmax(dim=1), I get this error:
`Traceback (most recent call last):
  File "main.py", line 274, in <module>
    main(args)
  File "main.py", line 203, in main
    logger.add([predictions.cpu(),y[:,0].cpu(),t], subset= 'train')
  File "/home/stek/.local/lib/python3.8/site-packages/continuum/metrics/base_logger.py", line 51, in add
    self._add_perf(predictions, targets, task_ids, subset)
  File "/home/stek/.local/lib/python3.8/site-packages/continuum/metrics/base_logger.py", line 74, in _add_perf
    predictions = convert_numpy(predictions)
  File "/home/stek/.local/lib/python3.8/site-packages/continuum/metrics/base_logger.py", line 9, in convert_numpy
    tensor = tensor.cpu().numpy()
RuntimeError: Can't call numpy() on Tensor that requires grad. Use tensor.detach().numpy() instead.`

Btw, I followed what Arthur has done in the script engine.py, line 259 of the DyTox model (logger.add([output.cpu().argmax(dim=1), target.cpu(), task_ids], subset='test')).

**Comment by TLESORT** [comment]
I think I have found the problem.
you might call, `logger.end_epoch()` and `logger.end_task()` sequentially which create a bug.
If you do not call end_epoch for your last epoch it should be ok.
This is the minimal example I created from what I understood was your use case.
````
logger = Logger(list_subsets=['train', 'test'])
    nb_tasks = 3
    nb_epochs = 5
    nb_iteration = 6
    for task in range(nb_tasks):
        for epoch in range(nb_epochs):
            for iteration in range(nb_iteration):
                preds = np.random.randint(0, 10 + 1, 64)
                targets = np.random.randint(0, 10 + 1, 64)
                task_ids = np.ones(64) * task
                logger.add(value=[preds, targets, task_ids], subset='train')
                preds_te = np.random.randint(0, 10 + 1, 64)
                targets_te = np.random.randint(0, 10 + 1, 64)
                logger.add(value=[preds_te, targets_te, task_ids], subset='test')
                assert 0. <= logger.accuracy <= 1.
            assert 0. <= logger.average_incremental_accuracy <= 1.
            if epoch != nb_epochs-1:
                logger.end_epoch()
        logger.end_task()
```
Tell me if it solve your problem.

I will try to fix, this, it is really not intuitive... sorry

**Comment by TLESORT** [comment]
if it was indeed your problem, I have made a fix, that we will merge soon.
https://github.com/Continvvm/continuum/pull/268

**Comment by umbertocappellazzo** [comment]
Hmm, I don't understand why I should add another round of iterations (nb_iterations). In fact it wasn't clear for me how to place correctly end_task() and end_epoch(). If I train and iterate through the test_set at each epoch, the problem should not be present right? The problem is that I do test only at some intervals. I put the logger.end_task() at the end of the task loop as the last thing in my code. But I don't understand why some metrics were correctly computed and others were not. 
So, shouldn't be called end_epoch() during thr last epoch for whatever experiment someone is running or is it something related to my case only? Cuz in your documentatin there is this example: 
`from continuum.metrics import Logger

model = ... Initialize your model here ...

list_keywords=["latent_vector"]

logger = Logger(list_keywords=list_keywords, list_subsets=['train', 'test'])

for tasks in task_scenario):
    for epoch in range(epochs)
        for x, y, t in task_loader:
            # Do here your model training with losses and optimizer...
        latent_vector = model.get_latent_vector_fancy_method_you_designed()
        logger.add(latent_vector, keyword='latent_vector', subset="train")
        logger.end_epoch()

    logger.end_task()`

I was sticking to it for my case, and logger.end_epoch() is called also in the last epoch.

**Comment by umbertocappellazzo** [comment]
I was a bit buffled cuz I call logger.add at each epoch for the "train", whereas I call it only at some intervals for the "test". This is what is different from the standard examples I saw in your docs. Am I right? And I didn't know if I had to apply some modifications to the logger.

**Comment by TLESORT** [comment]
1-in the example I made, I created multi iteration to simulate multiple mini-batches
2- every time you use logger.add(...), it concatenates your results to a vector. using end_epoch() create a new vector for the epoch in a dictionary. There are one dictionary per task, so end_task create a new dictionary. 
3- the mismatch between the number of log for train and for test should not be a problem.
4-the example in the documentation might be wrong... (but with the PR I have done it should be ok)

**Comment by umbertocappellazzo** [comment]
Ok! So, now it should work and I should not make any modification to my code. I'm gonna write to ya in Twitter may the issue persist. Now that Arthur has also corrected the issue with the fluentspeech dataset, everything should work fine. Thx for your help! 🤗

**Comment by TLESORT** [comment]
I just merged `fluentspeech` branch to master, so you can use `fix_metrics` branch to have the updated logger.
Thanks for reporting errors ! :)

**Comment by arthurdouillard** [comment]
Btw, you can also upgrade your continuum version to 1.2.3, it releases both the fix to the metrics and the fluentspeech datasets.

**Comment by umbertocappellazzo** [comment]
@arthurdouillard I upgraded continuum to the version 1.2.3., but it says `ImportError: cannot import name 'FluentSpeech' from 'continuum.datasets' (/home/stek/.local/lib/python3.8/site-packages/continuum/datasets/__init__.py)`.
In fact the file is not present. Can u cast a glance over it? Thx.
