### ISSUE TITLE
np.mean() or torch.mean()

### ISSUE THREAD

**Issue by DoubleClass** [Continvvm/continuum#278]
in rehearsal/herding.py line 99, this is a:
`mu = np.mean(D, axis=1)`
every time I try to run code with rehearsal memory, here come this bug:
`  File "main.py", line 219, in continual_clip
    memory.add(
  File "/root/anaconda3/envs/clip/lib/python3.8/site-packages/continuum/rehearsal/memory.py", line 179, in add
    mem_x, mem_y, mem_t = self.herding_method(x, y, t, z, nb_per_class=self.memory_per_class)
  File "/root/anaconda3/envs/clip/lib/python3.8/site-packages/continuum/rehearsal/herding.py", line 99, in herd_closest_to_barycenter
    mu = np.mean(D, axis=1)
  File "<__array_function__ internals>", line 180, in mean
  File "/root/anaconda3/envs/clip/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 3430, in mean
    return mean(axis=axis, dtype=dtype, out=out, **kwargs)
TypeError: mean() received an invalid combination of arguments - got (out=NoneType, dtype=NoneType, axis=int, ), but expected one of:
 * (*, torch.dtype dtype)
 * (tuple of ints dim, bool keepdim, *, torch.dtype dtype)
 * (tuple of names dim, bool keepdim, *, torch.dtype dtype)`

when I change this to torch.mean(), code running ok

**Comment by TLESORT** [comment]
Hi @DoubleClass ,
Sorry for the late reply, and thank you for the issue.
The error you get is strange since everything is supposed to be numpy vectors. However, the error message mentioned torch, so maybe your input data is composed of torch tensors. Did you check this already?

**Comment by TLESORT** [comment]
I close it for now; feel free to reopen it if you still have the problem.
