### ISSUE TITLE
Package `requirements.txt` into PyPI tarball

### ISSUE THREAD

**Issue by thomas-bouvier** [Continvvm/continuum#279]
I'm working on creating a Spack recipe for this package. However, I noticed that the tarball hosted on PyPI doesn't contain the `requirements.txt` file. Would it be possible to include it in the next release? Thanks.

**Comment by TLESORT** [comment]
Hu @thomas-bouvier, we will add it to the next release. Thank you for the issue :)

**Comment by TLESORT** [comment]
Done 👌

**Comment by thomas-bouvier** [comment]
Thanks :)
