### ISSUE TITLE
bug in forgetting metric

### ISSUE THREAD

**Issue by jinghan-he** [Continvvm/continuum#281]
```
def forgetting(all_preds, all_targets, all_tasks):
    """Measures the average forgetting.

    Reference:
    * Riemannian Walk for Incremental Learning: Understanding Forgetting and Intransigence
      Chaudhry et al. ECCV 2018

    See eq. 3.
    """
    k = len(all_preds)  # Number of seen tasks so far
    # TODO if we take in account zeroshot, we should take the max of all_tasks?
    if k <= 1:
        return 0.

    f = 0.
    for j in range(k - 2):
        # Accuracy on task j after learning current task k
        a_kj = _get_R_ij(k - 1, j, all_preds, all_targets, all_tasks)
        # Best previous accuracy on task j
        max_a_lj = max(_get_R_ij(l, j, all_preds, all_targets, all_tasks) for l in range(k - 2) if l >= j)
        f += max_a_lj - a_kj  # We want this results to be as low as possible

    metric = f / (k - 1)
    assert -1.0 <= metric <= 1.0, metric
    return metric
```

`for j in range(k-2)` should be `for j in range(k-1)`, otherwise after the k_th task only the first k-2 tasks are considered and the denominator when averaging over past tasks is  is also mistaken.

**Comment by TLESORT** [comment]
Hi @Jillian-h ,
Thanks for your issue.
The index issue is already fixed in the master branch (and also on the pip version, I believe); where did you get this version of the code?
Have a nice day.
Timothée

Here is the line on main branch: https://github.com/Continvvm/continuum/blob/master/continuum/metrics/metrics.py#L168

**Comment by TLESORT** [comment]
I believe this issue is solved, so I close it. Feel free to re-open it if needed.
