### ISSUE TITLE
Error: ModuleNotFoundError: No module named 'datasets.arrow_dataset'

### ISSUE THREAD

**Issue by NiccoBiondi** [Continvvm/continuum#282]
Hi there, 

I'm currently using continuum 1.2.7 but I got this error when trying to import CIFAR10. 
Here the traceback of the error:

```
File "/code/src/cl2r/main.py", line 17, in <module>
    from cl2r.utils import create_pairs, update_criterion_weight, BalancedBatchSampler
  File "/code/src/cl2r/utils.py", line 12, in <module>
    from continuum.datasets import CIFAR10
  File "/code/venv/lib/python3.10/site-packages/continuum/__init__.py", line 11, in <module>
    from continuum.scenarios import *
  File "/code/venv/lib/python3.10/site-packages/continuum/scenarios/__init__.py", line 14, in <module>
    from continuum.scenarios import hf
  File "/code/venv/lib/python3.10/site-packages/continuum/scenarios/hf/__init__.py", line 3, in <module>
    from continuum.scenarios.hf.huggingface_fellowship import HuggingFaceFellowship
  File "/code/venv/lib/python3.10/site-packages/continuum/scenarios/hf/huggingface_fellowship.py", line 4, in <module>
    from datasets.arrow_dataset import Dataset as HFDataset
ModuleNotFoundError: No module named 'datasets.arrow_dataset'
```

I've found this in the following two files:
https://github.com/Continvvm/continuum/blob/master/continuum/scenarios/hf/huggingface_continual.py#L5
https://github.com/Continvvm/continuum/blob/master/continuum/scenarios/hf/huggingface_continual.py#L5

and the problem is that is in [dataset](https://github.com/Continvvm/continuum/tree/master/continuum/datasets) there is no arrow_dataset.py file.

Can you fix it? 

Best Niccolò

**Comment by TLESORT** [comment]
Hi @NiccoBiondi,
Thanks for using continuum and for your issue.
There is a library called datasets `https://pypi.org/project/datasets/`, `arrow_dataset` is supposed to be from this library.
Can you tell me which version of this library do you have?
Have a nice day
Best
Timothée

**Comment by NiccoBiondi** [comment]
Hi Timothée, 
thanks for your reply!

I have installed the 2.11.0 version of the datasets packages.

Bests
Niccolò

**Comment by TLESORT** [comment]
If you do just:

```
import datasets
from datasets.arrow_dataset import Dataset as HFDataset
```
Does that work?

edit:
And what about? in a terminal
```
import continuum
from continuum.datasets import CIFAR10
```

**Comment by NiccoBiondi** [comment]
Yes it works, probably I got some package versions crash. 
I reinstalled again by virtual env and it works!

Thanks a lot, 
Niccolò
