### ISSUE TITLE
[Question] How to create scenario with N-way K-shot

### ISSUE THREAD

**Issue by kirk86** [Continvvm/continuum#286]
What would be the recommended way to create scenarios with N-classes and K-images per class?

Is something like that covered in the library, is there a way to define how many samples/images per class increment should be drawn?

For instance, for a given dataset with 100 classes one might want to have a scenario where during the 1st session/task the estimator is exposed to 55 classes using all samples/images corresponding to those 55 classes, then on session = 2,...,10, the estimator is shown 5 classes per session/task with only 3 samples/images from each of those 5 classes.

**Comment by TLESORT** [comment]
Hi @kirk86, 
thanks for your question.
I think you should be able to deal with this with the function:
> def get_balanced_sampler(taskset, log=False, num_samples=None, replacement=True, generator=None):

With something like this should do the job:

```
# taskset contains the current data that you want to subsample to get K images.
from continuum.dataset import CIFAR100
from torch.utils.data import DataLoader
dataset_train = CIFAR100("./Archives/", train=True)
scenario = ClassIncremental(
    dataset_train ,
    increment=5,
    initial_increment=55,
    transformations=[transforms.ToTensor()]
)
K=3
for task_id, tasksetin enumerate(cl_scenario):
    sampler = get_balanced_sampler(taskset, num_samples=K, replacement=False)
    loader = DataLoader(taskset, sampler=sampler, batch_size=1)
    for x, y, t in loader:
          .......
```

**Comment by kirk86** [comment]
Hi @TLESORT,
thanks for the reply.
That looks indeed something that might work. I gave it a try but it gives me results which I couldn't fully comprehend.

The goal is to create a scenario for few shot incremental learning, the estimator is trained on 55 classes initially until convergence then for the remaining 45 classes, the estimator is incrementally learning 5 classes at a time with only 3 samples for each of the remaining 45 classes. Also, assume that the user might provide an order into how the classes are shown to the estimator.

I've run the example you illustrated and got the following results:
<img width="814" alt="image" src="https://github.com/Continvvm/continuum/assets/2902390/5701ea1d-f76f-47b2-9fe8-7a692434cc0a">

It seems like the illustration is going through all classes [0-9] (if we look at the task id) and it doesn't go through the initial 55 classes.

I also think that the batch_size should not play a role here, for instance a user might ask for a batch_size of 32 samples, which can be accommodated in the initial task of learning 55 classes, but might raise issues for the remaining tasks of learning 45 classes per 5 class increment with only 3 samples. In that case the loader should return `min(k, batch_size)`

To make things a bit easier to understand, let's suppose that we have 10 tasks $t=1,\ldots,10$
at $t=1$ estimator is shown 55 classes according to user order, batch_size can be anything user sets
at $t=2$ estimator is shown 5 classes according to user order, with 3 samples, batch_size automatically adjusts to `min(k, batch_size)`
at $t=3,\ldots,10$ do as in task $t=2$ 

I hope it makes things a bit more clear?

**Comment by TLESORT** [comment]
Hi, 
Thanks for the clarification.
yes, you can choose whatever batch size you want, I just set 1 as default.

> It seems like the illustration is going through all classes [0-9]

I think it is more that it goes through tasks [0-9] but class values are not printed in your example.

The `get_balanced_sampler` function is only for task index >= 1 (you do not want to downsample the first task).
Maybe, you should use: (assuming 5 classes per task)

`sampler = get_balanced_sampler(taskset, num_samples=K*5, replacement=False)`

But I am not 100% sure that you will have exactly K data points per class, it might be only true on average.

Another solution could be to subsample the dataset at the beginning or the taskset before creating the dataloader.
Tell me if that helps :)

**Comment by kirk86** [comment]
Hi @TLESORT,

thanks again for your reply.

> I think it is more that it goes through tasks [0-9] but class values are not printed in your example.

You are right, my bad, I was confused, hence my ignorant questions so far 😄 .

> The `get_balanced_sampler` function is only for task index >= 1 (you do not want to downsample the first task).

This makes sense, but I'm still a bit confused, for instance I've modified the illustration by adding `class_order`

```
class_order = [68, 56, 78, 8, 23, 84, 90, 65, 74, 76, 40, 89, 3, 92, 55,
               9, 26, 80, 43, 38, 58, 70, 77, 1, 85, 19, 17, 50, 28, 53,
               13, 81, 45, 82, 6, 59, 83, 16, 15, 44, 91, 41, 72, 60, 79,
               52, 20, 10, 31, 54, 37, 95, 14, 71, 96, 98, 97, 2, 64, 66,
               42, 22, 35, 86, 24, 34, 87, 21, 99, 0, 88, 27, 18, 94, 11,
               12, 47, 25, 30, 46, 62, 69, 36, 61, 7, 63, 75, 5, 32, 4,
               51, 48, 73, 93, 39, 67, 29, 49, 57, 33]

# taskset contains the current data that you want to subsample to get K images.
dataset_train = ctnum.datasets.CIFAR100("./data/cifar100/", train=True, download=False)
scenario = ctnum.ClassIncremental(
    dataset_train,
    increment=5,
    initial_increment=55,
    transformations=[tv.transforms.ToTensor()],
    class_order = class_order
)

K=3

for task_id, taskset in enumerate(scenario):
    sampler = ctnum.tasks.utils.get_balanced_sampler(taskset, num_samples=K, replacement=False)
    loader = torch.utils.data.DataLoader(taskset, sampler=sampler, batch_size=32)
    
    for i, (x, y, task) in enumerate(loader):
        print("task_id: ", task_id, "x: ", x.shape, "y: ", y,)
```

And, now the results are the following:
```
task_id:  0 x:  torch.Size([3, 3, 32, 32]) y:  tensor([21, 38,  7])
task_id:  1 x:  torch.Size([3, 3, 32, 32]) y:  tensor([56, 56, 58])
task_id:  2 x:  torch.Size([3, 3, 32, 32]) y:  tensor([62, 63, 63])
task_id:  3 x:  torch.Size([3, 3, 32, 32]) y:  tensor([67, 66, 67])
task_id:  4 x:  torch.Size([3, 3, 32, 32]) y:  tensor([71, 72, 73])
task_id:  5 x:  torch.Size([3, 3, 32, 32]) y:  tensor([77, 75, 78])
task_id:  6 x:  torch.Size([3, 3, 32, 32]) y:  tensor([83, 83, 82])
task_id:  7 x:  torch.Size([3, 3, 32, 32]) y:  tensor([87, 87, 85])
task_id:  8 x:  torch.Size([3, 3, 32, 32]) y:  tensor([93, 91, 90])
task_id:  9 x:  torch.Size([3, 3, 32, 32]) y:  tensor([97, 95, 96])
```

Here's where I'm confused, the CIFAR100 dataset has 50K training images.
Then, for `task_id: 0` shouldn't we expect to see approximately 30K images according to the 
```
class_order = [68, 56, 78, 8, 23, 84, 90, 65, 74, 76, 40, 89, 3, 92, 55,
               9, 26, 80, 43, 38, 58, 70, 77, 1, 85, 19, 17, 50, 28, 53,
               13, 81, 45, 82, 6, 59, 83, 16, 15, 44, 91, 41, 72, 60, 79,
               52, 20, 10, 31, 54, 37, 95, 14, 71, 96,]
```
Then, for `task_id > 0` we should expect to see the next 5 classes in our `class_order` list
```
class_order = [98, 97, 2, 64, 66]
```
where for each class we see 3 samples.

So, the results when iterating over the loader should be something like:
```
task_id:  0 x:  torch.Size([32, 3, 32, 32]) y:  tensor([68, 56, 78, 8, 23, 84, 90, 65, 74, 76, 40, 89, 3, 92, 55,
               9, 26, 80, 43, 38, 58, 70, 77, 1, 85, 19, 17, 50, 28, 53,
               13, 81])
task_id:  0 x:  torch.Size([32, 3, 32, 32]) y:  tensor([45, 82, 6, 59, 83, 16, 15, 44, 91, 41, 72, 60, 79,
               52, 20, 10, 31, 54, 37, 95, 14, 71, 8, 90, 40, 3, 1, 13, 9, 23, 3, 26])
.
.
.

task_id:  1 x:  torch.Size([15, 3, 32, 32]) y:  tensor([98, 97, 2, 64, 66, 2, 64, 97, 98, 66, 98, 97, 2, 64, 66])
task_id:  2 x:  torch.Size([15, 3, 32, 32]) y:  tensor([42, 22, 35, 86, 24, 35, 22, 86, 42, 24, 42, 22, 35, 86, 24])
.
.
.
task_id:  9 x:  torch.Size([15, 3, 32, 32]) y:  tensor([34, 87, 21, 99, 0, 21, 99, 87, 34, 0, 34, 87, 21, 99, 0])
```

It seems that the `batch_size` argument in the `DataLoader` is not being respected, if I'm not mistaken?

**Comment by TLESORT** [comment]
> It seems that the batch_size argument in the DataLoader is not being respected, if I'm not mistaken?

I think it is respected, but as you kept the K=3 and subsample, you can not have more than 3 samples.

> Then, for task_id > 0 we should expect to see the next 5 classes in our class_order list

To simplify the processing of data in continuum, when you use a different class order, we just remap the class labels. So classes 0 and 1 are the original classes 68, 56 (given your ordering). (plotting images should confirm that)

**Comment by TLESORT** [comment]
I tested the code with the sampler and in the end, the number of samples per class is not exactly the right one every time.
So the less-elegant way to create your scenario is the following:

```
import torch
import continuum as ctnum
import numpy as np
from continuum import TaskSet

# taskset contains the current data that you want to subsample to get K images.
dataset_train = ctnum.datasets.CIFAR100("./data/cifar100/", train=True, download=False)
scenario = ctnum.ClassIncremental(
    dataset_train,
    increment=5,
    initial_increment=55
)

K=3

for task_id, taskset in enumerate(scenario):

    if task_id > 0:
        subset = None
        classes = taskset.nb_classes

        x, y, _ = taskset.get_raw_samples()
        for class_ in taskset.get_classes():
            indexes = np.where(y == class_)[0]
            select_indexes = np.random.choice(indexes, K, replace=False)
            if subset is None:
                subset = TaskSet(x[select_indexes].copy(), y[select_indexes].copy(), None, taskset.trsf,
                        data_type=taskset.data_type)
            else:
                subset.add_samples(x[select_indexes].copy(), y[select_indexes].copy())
        taskset = subset
    loader = torch.utils.data.DataLoader(taskset, batch_size=32)
    
    for i, (x, y, task) in enumerate(loader):
        print("task_id: ", task_id, "x: ", x.shape, "y: ", y.sort()[0],)
        if i > 5:
            break
```

**Comment by kirk86** [comment]
Hi @TLESORT,
appreciate all the help. Thanks a lot.
This indeed looks to cover the scenario mentioned.
I only have one last question if you don't mind me asking.
Does the loader or more appropriately iterating over the loader does it go over all the data in the dataset, all 50K?
```
task_id:  0 x:  torch.Size([32, 3, 32, 32]) y:  tensor([ 1,  2,  2,  3,  3,  4,  5,  5,  6,  6,  7,  8,  9, 11, 17, 21, 23, 25,
        26, 26, 28, 31, 32, 33, 35, 35, 45, 48, 52, 53, 53, 54])
task_id:  0 x:  torch.Size([32, 3, 32, 32]) y:  tensor([ 0,  1,  3,  4,  5, 11, 11, 13, 14, 14, 15, 18, 19, 19, 21, 22, 27, 29,
        29, 29, 34, 35, 36, 36, 38, 38, 42, 46, 46, 51, 53, 54])
task_id:  0 x:  torch.Size([32, 3, 32, 32]) y:  tensor([ 0,  2,  7,  8,  8,  9, 10, 16, 17, 18, 18, 24, 25, 25, 28, 28, 29, 31,
        31, 32, 33, 39, 42, 42, 44, 44, 44, 45, 46, 48, 49, 51])
task_id:  0 x:  torch.Size([32, 3, 32, 32]) y:  tensor([ 0,  3,  4,  4,  6,  6,  7,  7, 10, 10, 11, 11, 15, 19, 22, 25, 28, 30,
        31, 32, 41, 44, 44, 45, 47, 49, 49, 50, 50, 51, 52, 54])
task_id:  0 x:  torch.Size([32, 3, 32, 32]) y:  tensor([ 0,  1,  1,  2,  2,  3,  4,  5,  6,  7, 16, 17, 18, 18, 23, 23, 24, 25,
        27, 28, 29, 30, 33, 33, 34, 36, 39, 40, 41, 43, 47, 48])
task_id:  0 x:  torch.Size([32, 3, 32, 32]) y:  tensor([ 0,  4,  5,  7,  9, 12, 12, 16, 17, 17, 18, 22, 25, 28, 33, 33, 33, 38,
        40, 42, 43, 43, 44, 46, 47, 48, 49, 49, 50, 53, 54, 54])
task_id:  0 x:  torch.Size([32, 3, 32, 32]) y:  tensor([ 0,  1,  1,  7,  7,  9, 10, 11, 11, 12, 12, 12, 13, 14, 15, 16, 20, 20,
        24, 25, 29, 30, 30, 34, 35, 36, 38, 39, 46, 47, 51, 54])
task_id:  1 x:  torch.Size([15, 3, 32, 32]) y:  tensor([55, 55, 55, 56, 56, 56, 57, 57, 57, 58, 58, 58, 59, 59, 59])
task_id:  2 x:  torch.Size([15, 3, 32, 32]) y:  tensor([60, 60, 60, 61, 61, 61, 62, 62, 62, 63, 63, 63, 64, 64, 64])
task_id:  3 x:  torch.Size([15, 3, 32, 32]) y:  tensor([65, 65, 65, 66, 66, 66, 67, 67, 67, 68, 68, 68, 69, 69, 69])
task_id:  4 x:  torch.Size([15, 3, 32, 32]) y:  tensor([70, 70, 70, 71, 71, 71, 72, 72, 72, 73, 73, 73, 74, 74, 74])
task_id:  5 x:  torch.Size([15, 3, 32, 32]) y:  tensor([75, 75, 75, 76, 76, 76, 77, 77, 77, 78, 78, 78, 79, 79, 79])
task_id:  6 x:  torch.Size([15, 3, 32, 32]) y:  tensor([80, 80, 80, 81, 81, 81, 82, 82, 82, 83, 83, 83, 84, 84, 84])
task_id:  7 x:  torch.Size([15, 3, 32, 32]) y:  tensor([85, 85, 85, 86, 86, 86, 87, 87, 87, 88, 88, 88, 89, 89, 89])
task_id:  8 x:  torch.Size([15, 3, 32, 32]) y:  tensor([90, 90, 90, 91, 91, 91, 92, 92, 92, 93, 93, 93, 94, 94, 94])
task_id:  9 x:  torch.Size([15, 3, 32, 32]) y:  tensor([95, 95, 95, 96, 96, 96, 97, 97, 97, 98, 98, 98, 99, 99, 99])
```
Since `task_id=0` contains 55 classes with corresponding approximately ~30K images from the total 50K in dataset, then if we divide the 30K images by a `batch_size=32` we would expect the numbers of `rows` printed with `task_id=0` to repeat approximately ~937, instead here we see `task_id=0` to be printed only 7 times.

Maybe I have misunderstood something?

**Comment by TLESORT** [comment]
Did you keep the:
```
if i > 5:
            break
```
Just remove it and it should be fine. (it was there just to not print too much lines)

**Comment by kirk86** [comment]
Great, I initially removed that but was getting similar results, I suppose jupyter was holding some hidden state, after restarting kernel it works just fine 😄 

On a side note, for `task_id >0` the class labels shown are always the same even when adding `shuffle` in the loader or when using different splits of the data `train` vs `valid`.

```
task_id:  1 x:  torch.Size([15, 3, 32, 32]) y:  tensor([55, 55, 55, 56, 56, 56, 57, 57, 57, 58, 58, 58, 59, 59, 59])
task_id:  2 x:  torch.Size([15, 3, 32, 32]) y:  tensor([60, 60, 60, 61, 61, 61, 62, 62, 62, 63, 63, 63, 64, 64, 64])
task_id:  3 x:  torch.Size([15, 3, 32, 32]) y:  tensor([65, 65, 65, 66, 66, 66, 67, 67, 67, 68, 68, 68, 69, 69, 69])
task_id:  4 x:  torch.Size([15, 3, 32, 32]) y:  tensor([70, 70, 70, 71, 71, 71, 72, 72, 72, 73, 73, 73, 74, 74, 74])
task_id:  5 x:  torch.Size([15, 3, 32, 32]) y:  tensor([75, 75, 75, 76, 76, 76, 77, 77, 77, 78, 78, 78, 79, 79, 79])
task_id:  6 x:  torch.Size([15, 3, 32, 32]) y:  tensor([80, 80, 80, 81, 81, 81, 82, 82, 82, 83, 83, 83, 84, 84, 84])
task_id:  7 x:  torch.Size([15, 3, 32, 32]) y:  tensor([85, 85, 85, 86, 86, 86, 87, 87, 87, 88, 88, 88, 89, 89, 89])
task_id:  8 x:  torch.Size([15, 3, 32, 32]) y:  tensor([90, 90, 90, 91, 91, 91, 92, 92, 92, 93, 93, 93, 94, 94, 94])
task_id:  9 x:  torch.Size([15, 3, 32, 32]) y:  tensor([95, 95, 95, 96, 96, 96, 97, 97, 97, 98, 98, 98, 99, 99, 99]
``` 
Is that correct?

```
class_order = [68, 56, 78, 8, 23, 84, 90, 65, 74, 76, 40, 89, 3, 92, 55,
               9, 26, 80, 43, 38, 58, 70, 77, 1, 85, 19, 17, 50, 28, 53,
               13, 81, 45, 82, 6, 59, 83, 16, 15, 44, 91, 41, 72, 60, 79,
               52, 20, 10, 31, 54, 37, 95, 14, 71, 96, 98, 97, 2, 64, 66,
               42, 22, 35, 86, 24, 34, 87, 21, 99, 0, 88, 27, 18, 94, 11,
               12, 47, 25, 30, 46, 62, 69, 36, 61, 7, 63, 75, 5, 32, 4,
               51, 48, 73, 93, 39, 67, 29, 49, 57, 33]

# taskset contains the current data that you want to subsample to get K images.
dataset_train = ctnum.datasets.CIFAR100("./data/cifar100/", train=True, download=False)
scenario = ctnum.ClassIncremental(
    dataset_train,
    increment=5,
    initial_increment=55,
    class_order=class_order
)

def iterate_scenario(scenario, K=3, split=None):

    for task_id, taskset in enumerate(scenario):
        if split:
            taskset_train, taskset_valid = ctnum.tasks.split_train_val(taskset, val_split=0.1)
            if split == "train":
                taskset = taskset_train
            elif split == "valid":
                taskset = taskset_valid

        if task_id > 0:
            subset = None
            classes = taskset.nb_classes

            x, y, _ = taskset.get_raw_samples()
            for class_ in taskset.get_classes():
                indexes = np.where(y == class_)[0]
                select_indexes = np.random.choice(indexes, K, replace=False)
                if subset is None:
                    subset = ctnum.TaskSet(x[select_indexes].copy(), y[select_indexes].copy(), None, taskset.trsf,
                            data_type=taskset.data_type)
                else:
                    subset.add_samples(x[select_indexes].copy(), y[select_indexes].copy())
            taskset = subset

        loader = torch.utils.data.DataLoader(taskset, batch_size=32, shuffle=True)

        for i, (x, y, task) in enumerate(loader):
            print("task_id: ", task_id, "x: ", x.shape, "y: ", y.sort()[0],)
```

**Comment by TLESORT** [comment]
I think your issue is solved so I will close it.
Feel free to reopen it, if it is needed.

> the class labels shown are always the same even when adding shuffle

it is because I sorted them to in the print, replace `y.sort()[0]` by `y` and you will see the actual order.

Have a good day. :)
