### ISSUE TITLE
[Question] Class incremental scenario exhibits inverse accuracy per task compared to expected norm

### ISSUE THREAD

**Issue by kirk86** [Continvvm/continuum#288]
Hi there,

I've observed that when using a [class incremental scenario](https://continuum.readthedocs.io/en/latest/tutorials/scenarios/scenarios.html) I always get quite unexpected results compared to all the papers I've seen.

For instance, suppose we have the following scenario with tasks $T=10$, with base classes $B= 55$ and incremental classes per task $I_{T} = 5$.

We train the model on this scenario and then test it on the test data adhering to the same scenario. I've noticed that the accuracy between tasks increases instead of dropping (also happening with validation and train part of data). Below, shows accuracy of model on test data per task scenario (left-to-right).

`[28.27272726024281, 35.799999938964845, 32.400000274658204, 28.199999786376953, 19.199999877929688, 29.999999938964844, 26.5999998626709, 36.599999725341796, 56.40000030517578, 85.2000001220703]`

 One would expect to get high accuracy in the first task since it has 55 classes and a larger number of data samples and as we progress to the other incremental tasks accuracy would drop due to having less samples. Instead, what we observe is the opposite and I'm not sure whether its a bug or something else is going on.

I did some variations, playing with `class_order` but didn't seem to affect anything, more or less same behaviour.

**Comment by TLESORT** [comment]
Hi @kirk86,
Thanks for your question.
Generally speaking the more classes you have in a task the harder it is to get a high accuracy ( roughly speaking because the solution lies in a space of higher dimensionality). So, it looks normal that the first task gets a bit less accuracy (even if later tasks may suffer from loss of plasticity).
Also, the accuracy on the first task is lower after training on the other one because of forgetting, so it would be a second factor explaining the low performance.
So, it looks quite normal in my opinion.
Tell me if my explanation does not make sense to you.
Have a nice day.

PS: In many papers, the accuracy reported is not the accuracy per task at the end of the training but the accuracy at the time of training for each task. Each accuracy is therefore computed with weights from a different time point. So indeed, in such cases, the accuracy of the first tasks is higher than the accuracy of the later tasks.

**Comment by kirk86** [comment]
> PS: In many papers, the accuracy reported is not the accuracy per task at the end of the training but the accuracy at the time of training for each task. Each accuracy is therefore computed with weights from a different time point. So indeed, in such cases, the accuracy of the first tasks is higher than the accuracy of the later tasks

@TLESORT 
Thanks for reminding me of this that's what I'm doing, hence the reason for finding it a bit bizarre even though I agree with the remaining comments.

Let's see if I can make this  more clear. Suppose we have the following tasks $t_{t}, t_{2}, t_{3}, \ldots, t_{n}$. During training the model is trained on $t_{1}$ and evaluated on the validation and test part of $t_{1}$, then proceeds to being trained on $t_{2}$ utilizing the already learned weights/params from $t1$ (not starting from randomly initialized weights/params). Once it is trained on $t_{2}$, its evaluated on validation and test part of $t_{2}$, then proceeds to train on $t_{3}$ with the weights/params learned from $t_{2}$, when it finishes training on $t_{3}$ it is evaluated on the validation and test part of $t_{3}$, etc.

**Comment by TLESORT** [comment]
So, the accuracies you reported are only task-specific (the first is about classes 0-54, the second 54-59, ....)and were calculated at different time points, right?

Did you calculate them yourself or did you use one tool of continuum?
How long did you train on each task?
I would be interested to also see the result with equal size of tasks.

**Comment by kirk86** [comment]
> So, the accuracies you reported are only task-specific (the first is about classes 0-54, the second 54-59, ....)and were calculated at different time points, right?

Yes, so I've tried to compute accuracy on each task with weights both randomly initialized for each task and weights from previous task while learning current task. The pattern is the same.

> Did you calculate them yourself or did you use one tool of continuum?

Both, the same pattern occurs.

> How long did you train on each task?

I've tried as few as 10 epochs per task and as many as 100 epochs per task, same pattern.

> I would be interested to also see the result with equal size of tasks

It's the same pattern when training with 10 base classes and 10 increments. You can verify by using cifar100 and any model, e.g., resnet18 or resnet20. 

Initially we have the first task reporting higher accuracy, the next 2 tasks lower, and then goes up and down with later tasks reaching quite high accuracy.

**Comment by TLESORT** [comment]
So, based on what you told me, if you sample classes [0-9] as the first task, and train a model from scratch, you will not get the same accuracy as if you sample the same classes for the second task and train from scratch?

Can I see the code that creates your scenario?

**Comment by kirk86** [comment]
> So, based on what you told me, if you sample classes [0-9] as the first task, and train a model from scratch, you will not get the same accuracy as if you sample the same classes for the second task and train from scratch?

Assuming we are in a class incremental scenario with 10 base classes and 10 increment classes.
Shouldn't that be $[0-9]$ classes for task $t_{1}$, $[10-19]$ for task $t_{2}$, $[20-29]$ for task $t_{3}$, $\ldots$?

> Can I see the code that creates your scenario?

```
my_class_order = [68, 56, 78, 8, 23, 84, 90, 65, 74, 76, 40, 89, 3, 92, 55,
                         9, 26, 80, 43, 38, 58, 70, 77, 1, 85, 19, 17, 50, 28, 53,
                         13, 81, 45, 82, 6, 59, 83, 16, 15, 44, 91, 41, 72, 60, 79,
                         52, 20, 10, 31, 54, 37, 95, 14, 71, 96, 98, 97, 2, 64, 66,
                         42, 22, 35, 86, 24, 34, 87, 21, 99, 0, 88, 27, 18, 94, 11,
                         12, 47, 25, 30, 46, 62, 69, 36, 61, 7, 63, 75, 5, 32, 4,
                         51, 48, 73, 93, 39, 67, 29, 49, 57, 33]
transforms = your_dataset_transformations
dataset = ctnum.datasets.CIFAR100(data_path, train=is_train, download=True)
scenario = ctnum.ClassIncremental(
        dataset,
        initial_increment=10,
        increment=10,
        transformations=transforms,
        class_order=my_class_order
 )
```

I've tried with and without `my_class_order` and not much changed. Also, I've tried with `initial_increment=55` and `increment=5`, still same results.

In other words, I can't replicate the following diagram shown in most class incremental learning scenarios where the accuracy drops off gradually as you proceed to the next incremental tasks, $T=10$ stands for 10 incremental tasks.
<img width="400" alt="image" src="https://github.com/Continvvm/continuum/assets/2902390/a40a0955-ce2f-48eb-8203-74b408cc65cb">

**Comment by TLESORT** [comment]
> Shouldn't that be classes [0-9] for task 1, [10-19] for task , for task 2 ?
Yes absolutely, I was just trying to imagine an alternative scenario to detect potential unexpected behavior.

I am a bit confused because you spoke about evaluating each task alone  (https://github.com/Continvvm/continuum/issues/288#issuecomment-1791458629)  and if I am not mistaken the graph you show me, plot the all tasks seen so far accuracy.
I believe that if you plot the evolution of accuracy on all tasks seen so far you should get the same thing.

**Comment by kirk86** [comment]
> I am a bit confused because you spoke about evaluating each task alone ([#288 (comment)](https://github.com/Continvvm/continuum/issues/288#issuecomment-1791458629)) and if I am not mistaken the graph you show me, plot the all tasks seen so far accuracy.

How do you interpret plotting the accuracy for all tasks seen?
My interpretation is the following I have $T=10$ tasks and each task has 3 subsets, `[train, valid, test]`. You start training sequentially from task $t=0$ to task $t=T$, for each task you get the accuracy on each subset `[train, valid, test]` after finishing all epochs, you plot the accuracy for `[valid, test]` which basically is the evolution of accuracy across tasks.

> I believe that if you plot the evolution of accuracy on all tasks seen so far you should get the same thing.

Can you provide a minimal working example where you achieve to replicate the graph above for either scenario of `base classes=55, increment=5` or `base classes=10, increment=10`?

Here's what I get for the scenario `base classes=55, increment=5`, if you notice the graph there's an increase in accuracy as we move from initial tasks to the remaining ones, which is contradictory to the previous graph above, and that's what I'm trying to understand? Why? It's the same dataset as the one referenced from a paper for the same number of tasks. Also, same pattern happens for scenario `base classes=10, increment=10`.
<img width="300" alt="image" src="https://github.com/Continvvm/continuum/assets/2902390/a133eaf0-4831-43dd-9a67-62e4c21d33c5">

**Comment by TLESORT** [comment]
evaluation on all task seen so far is about:
1 - Training on tr_0, validation on val_0/test_0.
2 - Training on tr_1, validation on (val_0 + val_1)/(test_0 + test_1)
3 - ....

Sorry, I do not really have time to make a minimal example but you can look at the code from @arthurdouillard where he has similar result as your curve by using continuum here https://github.com/arthurdouillard/dytox

**Comment by kirk86** [comment]
Thanks, on a bit of a tangent line.
In the [docs](https://continuum.readthedocs.io/en/latest/tutorials/rehearsal/rehearsal.html#herding) regarding the example of `Rehearsal`, there's the following comment

```
# Important! Draw the raw samples from `scenario[task_id]` to
    # re-generate the taskset, otherwise you'd risk sampling from both new
    # data and memory data which is probably not what you want to do.
    memory.add(
        *scenario[task_id].get_raw_samples(), features
    )
```
Aren't these equivalent:
`memory.add(*scenario[task_id].get_raw_samples(), features) <==> memory.add(*taskset.get_raw_samples(), features)` ?

**Comment by TLESORT** [comment]
Hi @kirk86 , 
It is not equivalent because samples have been added to the taskset object (line  `taskset.add_samples(mem_x, mem_y, mem_t)` in the snippet of code) and you do not want to add samples that are already in the memory.
If the initial question is solved on your end, thanks to close the issue. :)
If the new question is not solved feel free to open a new issue ;)

**Comment by kirk86** [comment]
Thanks, closing for now on the first and will follow with new one regarding 2nd if needed be.
