### ISSUE TITLE
DataIncremental class should be implemented

### ISSUE THREAD

**Issue by TLESORT** [Continvvm/continuum#36]
NIC scenarios

**Comment by arthurdouillard** [comment]
NIC scenario can already be done in InstanceIncremental as we do for CORe50. Just need to specify the task ids of every samples.

Thus, I'm closing this issue but feel free to re-open it if you think I missed something.

**Comment by TLESORT** [comment]
Je reouvre temporairement pour qu'on en discute, quitte à refermer dans peu de temps ^^
