### ISSUE TITLE
Question Regarding Permuted MNIST

### ISSUE THREAD

**Issue by mmderakhshani** [Continvvm/continuum#37]
Hi,

May I ask you to provide me a snippet for loading data related to the permuted MNIST scenario? I assumed that the following one does the same. Is it right?
```
from continuum.datasets import MNIST
from continuum import InstanceIncremental
clloader = InstanceIncremental(MNIST(args.data, download=True),
                                nb_tasks=10,
                                train=True)
```

**Comment by TLESORT** [comment]
Hi @mmderakhshani ,

The instance incremental scenarios will only share existing instances of classes between n tasks, without doing any transformation.

To create the permutMNIST scenarios the class to use is Permutations

```
from continuum.datasets import MNIST
from continuum.scenarios import Permutations

clloader_train = Permutations(cl_dataset=MNIST(args.data, download=True, train=True),
                                                 nb_tasks=10,
                                                 seed=0)
```
You should be able to visualize data with:

```
for task_id, train_dataset in enumerate(clloader_train):
        train_dataset.plot(path=folder,
                                     title="MNIST_Permutations_{}.jpg".format(task_id),
                                     nb_samples=100,
                                      shape=[28, 28, 1])
```

Tell me if it works well for you :)

**Comment by mmderakhshani** [comment]
Ok. Thanks for your quick reply. I have installed your packages with `pip install continuum` and it seems that the installed package did not contain for example the **Permutation** class. Could you please update it?

**Comment by TLESORT** [comment]
I will try to do it asap, I tell you when it is done :)

**Comment by TLESORT** [comment]
It should be good now @mmderakhshani :)
