### ISSUE TITLE
Check that all datasets can be instanciated

### ISSUE THREAD

**Issue by arthurdouillard** [Continvvm/continuum#38]
https://github.com/Continvvm/continuum/pull/29#discussion_r470546096

We may have to create some dummy data for large datasets such as ImageNet.

**Comment by TLESORT** [comment]
Done with small dataset MNIST / KMNIST / Fashion-MNIST / CIFAR10 / CIFAR100

**Comment by arthurdouillard** [comment]
Also done for ImageFolder (which comprises ImageNet).
