### ISSUE TITLE
CIFAR-10/100 experiment of Zenke et al. (2017)

### ISSUE THREAD

**Issue by mmderakhshani** [Continvvm/continuum#45]
Hi @arthurdouillard,
Could you please tell me that your data loader API supports the CIFAR-10/100 experiment? This is an experiment I found in a paper called "continual learning with hyper-networks". BTW, I found there is a module named **Fellowship** which provides such a combination capability but I am not sure. May I ask you verify it?

**Comment by TLESORT** [comment]
I will answer for Arthur if you don't mind :)

I think the API does not support the CIFAR10/100 experiment from "continual learning with hyper-networks" yet.
The experiment is composed of 11 tasks, first CIFAR10 and after 10 tasks composed of set of 10 classes from CIFAR100, is that right?
If you need it, we can think about how to make it possible easily.

Fellowship is originally meant to use a composition of datasets, like first tasks : 'all cifar10' and second second 'all cifar100'. Maybe there is a smart way to use it for the experiment you mention. ;)

Cheers
Timothée

**Comment by TLESORT** [comment]
It seems there is a problem with the Fellowship class, I will try to fix it as soon as possible.
However normally the experiment you mentionned could be defined like this:

```
from continuum.datasets import CIFARFellowship
from continuum.scenarios import ClassIncremental

cl_dataset = CIFARFellowship(data_path=".", train=True)

continuum = ClassIncremental(cl_dataset, increment=10)

**Comment by TLESORT** [comment]
I've found a quick way to fix Fellowship you can replace lines 60-61 in continuum/datasets/base.py :
```
def __init__(self, *args, dataset_type, train: bool, **kwargs):
        super(PyTorchDataset, self).__init__(*args, train, **kwargs)
```

by 

```
def __init__(self, *args, dataset_type, data_path: str = "", train: bool, **kwargs):
        super(PyTorchDataset, self).__init__(*args, data_path, train, **kwargs)
```

After that, the code I gave in the previous comment should work and produce:
11 tasks
first tasks with CIFAR10, label from 0 to 9
second tasks, first 10 classes of CIFAR100, labels from 10 to 19
[...]
task eleven, last 10 classes of CIFAR100, labels from 100 to 119

I hope this is what you wanted :D

**Comment by arthurdouillard** [comment]
@mmderakhshani Fellowship currently has a small bug, but it will be fixed tomorrow. Sorry about that.

Yes we support the setting CIFAR10/CIFAR100, where there are 11 tasks of 10 classes each.

When the code will be fixed, you should do:

```
from continuum import ClassIncremental
from continuum.datasets import CIFARFellowship

dataset = CIFARFellowship("/my/data/path", train=True)
clloader = ClassIncremental(dataset, increment=[10 for _ in range(11)])
```

**Comment by mmderakhshani** [comment]
Hey, arthurdouillard and @TLESORT. Thanks for your warm support. so delighted to hear that your API will support cifar10/cifar100 benchmarks soon. To be honest, I am really enjoying your API and working with it.

**Comment by arthurdouillard** [comment]
@mmderakhshani Thimothée has fixed our bug, you can now use Continuum for the cifar10/100 benchmark!

Sorry again for the inconvenience.

If you find bugs, or have ideas for improvements, don't hesitate to create an issue or a pull request :)

**Comment by mmderakhshani** [comment]
@arthurdouillard 
Hi again,
I have installed your package again with pip install continuum==0.2.0. But I was suspicious about the test dataset. 

```
from continuum import ClassIncremental
from continuum.datasets import CIFARFellowship

dataset = CIFARFellowship("./data", train=True)
clloader = ClassIncremental(dataset, increment=10)
dataset_test = CIFARFellowship("./data", train=False)
clloader_test = ClassIncremental(dataset, increment=10)
```

I have checked the number of samples per each task during testing it is equal to 50000. Is it correct? The following code shows me the number of samples. could you please check the code?
```
for task_id, test_dataset in enumerate(clloader_test):
     print(len(test_dataset))
```
