### ISSUE TITLE
MultiNLI scenario triggers torchvision. ValueError: pic should be 2/3 dimensional. Got 1 dimensions.

### ISSUE THREAD

**Issue by nggih** [Continvvm/continuum#52]
Hi, I tried to investigate how continual learning can be implemented in my NLP classification project. When I tried to see the MultiNLI first and tried to figure out what inside the train_loader using for loop, but an error occured:
```
dataset = MultiNLI('./data')
scenario = InstanceIncremental(dataset)
for task_id, train_taskset in enumerate(scenario):
    print(task_id, dir(train_taskset))
    train_taskset, val_taskset = split_train_val(train_taskset, val_split=0.1)
    train_loader = DataLoader(train_taskset, batch_size=32, shuffle=True)
    val_loader = DataLoader(val_taskset, batch_size=32, shuffle=True)

   for x,y,t in train_loader:
      print(x, y, t)
```
![image](https://user-images.githubusercontent.com/8409460/93567305-a540af80-f9b8-11ea-9fd7-9bf34b77ae51.png)

For full code:
https://colab.research.google.com/drive/1R8rYCo-0wzoiIUTE64Pko-GtfwbGGQ9C#scrollTo=R2SHCM83-Omg

**Comment by arthurdouillard** [comment]
Hello, sorry about that but currently the DataLoader are not compatible with the MultiNLI dataset.
I'm not an expert in NLP, so I'm unsure what kind of loaders should we use (cf pytorch text).

If you want to use, simply grab the data in the taskset. It holds all data in its attributes `._x`, `._y`, and `._t`.

If you know a better way to handle text, please tell us!
