### ISSUE TITLE
Stream-51 dataset and others

### ISSUE THREAD

**Issue by DanielS684** [Continvvm/continuum#53]
Are you planning on adding other datasets?

**Comment by TLESORT** [comment]
Hi @DanielS684 , adding new datasets is not yet on the to-do list. But we can study specific needs :)
You would need the Stream-51 dataset?

**Comment by DanielS684** [comment]
@TLESORT Not really just seemed like an interesting dataset. Also, thanks for making this resource makes it so much easier for me to implement an idea I wanted to try.
