### ISSUE TITLE
imageio isn't listed as a dependency

### ISSUE THREAD

**Issue by lebrice** [Continvvm/continuum#54]
Hey there, thanks for your work!

imageio is used only at one place, in `viz.py`, and isn't listed as a dependency in the setup.py, therefore installing continuum via `pip install continuum` *works fine, but importing it raises an error

**Comment by arthurdouillard** [comment]
Hey, sorry about that.

I've push on master & released a new version on pypi (1.0.3) fixing that.

We now only use Pillow instead of imageio. It's a better choice I think because it's already a dependency of torchvision.
