### ISSUE TITLE
Stream-51

### ISSUE THREAD

**Issue by arthurdouillard** [Continvvm/continuum#67]

**Comment by TLESORT** [comment]
https://github.com/tyler-hayes/Stream-51

**Comment by arthurdouillard** [comment]
A bit annoying but it seems that the provided images must be cropped along side a particular bounding boxes, unique to the images.

So either, we do on our side this preprocessing or we must modify quite a lot the task set in order to incorpore that?
Any thoughts @TLESORT ? (not hurry at all)

**Comment by arthurdouillard** [comment]
Seems Hayes also propose another version of her dataset there https://github.com/ContinualAI/avalanche/tree/master/avalanche/benchmarks/datasets/stream51
