### ISSUE TITLE
Synbols domain ids

### ISSUE THREAD

**Issue by arthurdouillard** [Continvvm/continuum#68]
Currently Synbols dataset returns a task ids array of None because it's only available for class incremental.

Although we could use it in instance incremental by adding new domains every time, those domains could be the font. I think it exists for Synbols but I'm not sure yet where this information can be gathered.

**Comment by arthurdouillard** [comment]
See #84

**Comment by TLESORT** [comment]
Merged in https://github.com/Continvvm/continuum/commit/9e15e1a15dd9071ee3ff721df85ce4592e7d7ec1
