### ISSUE TITLE
Update logger more simple with more features 

### ISSUE THREAD

**Issue by TLESORT** [Continvvm/continuum#70]

**Comment by arthurdouillard** [comment]
Inspired from Keras' Callbacks, we could have only two methods:

- `add(...)`
- `epoch_end()`

**Comment by arthurdouillard** [comment]
https://keras.io/guides/writing_your_own_callbacks/

**Comment by TLESORT** [comment]
one function to add all type of results:
`logger.add(model(x), y, t, 'test')`
(or similar to this)

**Comment by TLESORT** [comment]
Callback function are more adapted for library thar that train models, no?

**Comment by arthurdouillard** [comment]
Not really, the philosophy is broader than that.
It's about composition (vs inheritance). 

But anyway I was just talking about the API of Keras's callback, not their actual usage. So we just need two methods `add`, and `end_epoch`.

**Comment by TLESORT** [comment]
simpliest example:

```
import Logger

logger = Logger()
for task in task_suite:
    for epoch in epoch_suite:
         logger.add([pred, y, t])
         logger.end_epoch()
    logger.end_task()
```

**Comment by TLESORT** [comment]
merged in https://github.com/Continvvm/continuum/commit/fc7be2f69fc012334ac8853008322eceb7f32f59
