### ISSUE TITLE
add NI scenario for core50 (not NIC)

### ISSUE THREAD

**Issue by TLESORT** [Continvvm/continuum#71]

**Comment by arthurdouillard** [comment]
I gave it a though and it works actually.

Either use `Core50` with `InstanceIncremental`. This dataset, contrary to the others variants of Core50, doesn't specify domain ids, so it's a "normal" dataset.

Or you could even use like `Core50v2_76` but specifying the `nb_tasks` in `InstanceIncremental`. In this case, we don't consider the domain ids.
