### ISSUE TITLE
PyPi package name

### ISSUE THREAD

**Issue by arthurdouillard** [Continvvm/continuum#9]
Continuum is already taken on PyPi, by a CI project from 2014.

We need a name for the PyPi, alternative choices:
- `lifelong`
- `deepcontinuum`
- `torchcontinuum`
...

EDIT: the owner of `Continuum` should give us soon the name.

**Comment by TLESORT** [comment]
Done thanks to Michel

**Comment by arthurdouillard** [comment]
Not yet, Michel didn't yet give us the name. Let keep this issue up until it's done :)
